const mongoose = require("mongoose");

const vagueSchema = mongoose.Schema({
	userId: { type: String },
	fermeId: { type: String },
	titre: { type: String, default: "" },
	qte_animaux: { type: Number, default: 0 },
	prix_animaux: { type: Number, default: 0 },
	coutParSujet: { type: Number, default: 0 },
	fournisseur: { type: String, default: "Non spécifié" },
	fournisseurId: { type: String, default: "" },
	date_arrive: { type: Date },
	animaux_perdu: { type: Number, default: 0 },
	valeur_animaux_perdu: { type: Number, default: 0 },
	transport: { type: Number, default: 0 },
	budget_prevu: { type: Number, default: 0 },
	benef_attendu: { type: Number, default: 0 },
	facture: { type: String, default: "Aucune facture" },
	etat: { type: String, default: 0 },
	age_sujet: { type: Number, default: 0 },
	poidsMoyen_sujet: { type: Number, default: 0 },
	NbreSujet_vendu: { type: Number, default: 0 },
	enStock: { type: Number, default: 0 },
	prixMoyenVente_sujet: { type: Number, default: 0 },
	budget_animaux: { type: Number, default: 0 },
	budget_aliments: { type: Number, default: 0 },
	budget_soins_medicaux: { type: Number, default: 0 },
	budget_amenagements: { type: Number, default: 0 },
	budget_location_local: { type: Number, default: 0 },
	budget_main_doeuvre: { type: Number, default: 0 },
	budget_electricite: { type: Number, default: 0 },
	budget_eau: { type: Number, default: 0 },
	budget_transport_vente: { type: Number, default: 0 },
	budget_autres_depenses: { type: Number, default: 0 },
	stoppe_le: { type: Date },
	created_at: { type: Date },
});

module.exports = mongoose.model("Vague", vagueSchema);
